# Generated by Django 4.2.3 on 2025-08-26 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, default='')),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('review_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reviewpage')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
