# Generated by Django 4.2.3 on 2025-08-28 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_review_rated_date_review_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rated_date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('result_json', models.JSONField()),
                ('rating_algorithm_key', models.CharField(max_length=50)),
                ('rating_model_key', models.CharField(max_length=50)),
                ('rating_model_priority', models.IntegerField()),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_scores', to='api.review')),
            ],
            options={
                'ordering': ['created'],
                'unique_together': {('rating_algorithm_key', 'rating_model_key', 'review')},
            },
        ),
    ]
