services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    #one-time for initialization with exact environment:
    #command: django-admin startproject trust_score . && python manage.py migrate
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
      - ./.env
    user: 1000:1000

  db:
    image: mariadb:11.8
    restart: unless-stopped
    env_file:
      - ./.env.dev
      - ./.env
    volumes:
      - mariadb_data:/var/lib/mysql
      - mariadb_logs:/var/log/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  mariadb_data:
    driver: local
  mariadb_logs:
    driver: local